name: Scala CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Install sbt
        run: |
          echo "Installing sbt..."
          wget https://piccolo.link/sbt-1.8.0.zip
          unzip sbt-1.8.0.zip
          sudo mv sbt /usr/local/bin

      - name: Cache SBT dependencies
        uses: actions/cache@v3
        with:
          path: ~/.sbt
          key: sbt-${{ runner.os }}-${{ hashFiles('**/*.sbt', '**/project/build.properties') }}
          restore-keys: |
            sbt-${{ runner.os }}-

      - name: Compile all modules
        run: sbt compile

      - name: Run tests in all modules
        run: sbt test
